global:
  sendAnonymousUsage: false
  checkNewVersion: false

api:
  # entryPoint: web
  insecure: false
  dashboard: true
  debug: true

log:
  #  filePath: "/etc/traefik/applog.log"
  #  format: json
  level: WARNING

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    # useBindPortIP: true
    exposedByDefault: false
    watch: true
    swarmMode: false

  file:
    filename: /etc/traefik/traefik_dynamic.yml
    watch: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: tricky@t4v.net
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
